apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset1
spec:
  selector:
    matchLabels:
      demotype: nginx-daemonset-demo1
  template:
    metadata:
     labels:
       demotype: nginx-daemonset-demo1
    spec:
      containers:
        - image: nginx
          name: nginx
      #nodeSelector:
       # gpupresent: "true"
