apiVersion: v1
kind: Pod
metadata:
   name: hostpath-pod
spec:
  containers:
    - image: redis
      name: redis-con
      volumeMounts:
         - name: test-vol
           mountPath: /test-mnt
  volumes:
    - name: test-vol
      hostPath:
        path: /test-vol

