apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  #completions: 2
  #parallelism: 2
  backoffLimit: 2
  template:
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["ls", "/nag"]
      restartPolicy: Never
