apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-vol1
spec:
   accessModes:
     - ReadWriteOnce
   capacity:
      storage: 10Gi
   gcePersistentDisk:
     pdName: my-data
     fsType: ext4
