apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: google-storage
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
parameters:
   type: pd-standard
   replication-type: regional-pd
#   zones: us-central1-a
volumeBindingMode: Immediate

mountOptions:
  - debug
allowVolumeExpansion: true
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - us-central1-a
