apiVersion: apps/v1
kind: ReplicaSet 
metadata:
   labels:
     run: busybox
   name: rs-busybox
spec:
  replicas: 2
  selector:
    matchLabels:
       run: busybox
  template:
    metadata:
      labels:
        run: busybox
    spec:
      volumes:
       - name: host-volume
         persistentVolumeClaim:
           claimName: pvc-hostpath
      containers:
       - image: busybox
         name: busybox
         command: ["/bin/sh"]
         args: ["-c", "sleep 600"]
         volumeMounts:
           - name: host-volume
             mountPath: /mydata
#  nodeSelector:
         #demoserver: "true"
