apiVersion: v1
kind: Pod
metadata:
   name: gce-pod
spec:
  containers:
    - image: busybox
      name: test-con
      volumeMounts:
        - name: test-gcepd
          mountPath: /test-gcepd
  volumes:
    - name: test-gcepd
      #persistentVolumeClaim:
       #  claimName: pvc-gce
      gcePersistentDisk:
        pdName: my-data-disk
          fsType: ext4
