apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-gce
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  gcePersistentDisk:
     pdName: my-data-disk
     fsType: ext4
