apiVersion: v1
kind: Pod
metadata:
   name: pv-pod
spec:
   containers:
      - name: testcon
        image: nginx
        volumeMounts:
           - name: test-volume
             mountPath: /test-pd
   volumes:
     - name: test-volume
       persistentVolumeClaim:
         claimName: pvc-gce
